### ISSUE TITLE
auto text replace

### ISSUE THREAD

**Issue by Axel-Erfurt** [frank038/Rubrica#1]
you are using in line 294

```python
    def text_edited(self, widget, path, text):
        # remove ";" and ":" from the text
        text = text.replace(";", "*").replace(":", "*")
```

Why? A homepage entry requires a colon.

**Comment by frank038** [comment]
> you are using in line 294
> 
> ```python
>     def text_edited(self, widget, path, text):
>         # remove ";" and ":" from the text
>         text = text.replace(";", "*").replace(":", "*")
> ```
> 
> Why? A homepage entry requires a colon.

A missed correction.

The module import_vcf.py has also been corrected.
